### ISSUE TITLE
Incorrect characters sqlite File

### ISSUE THREAD

**Issue by au-lait77** [Zeeshanahmad4/Zip-code-of-all-countries-cities-in-the-world-CSV-TXT-SQL-DATABASE#1]
In the SQLite DB, specifications with special characters are incorrect. See screenshot. There the characters ÖÄÜ are destroyed. in the TXT file everything is correct
Can u fix it?

![image](https://user-images.githubusercontent.com/13865833/91426393-c05a4c80-e85c-11ea-802f-e815ab1917c8.png)

**Comment by Zeeshanahmad4** [comment]
You need to edit your SQL encoding.
